export const PHASES = {
  menstrual: {
    name: 'Menstrual',
    emoji: '🌙',
    days: '1–5',
    bgColor: '#FCEBEB',
    textColor: '#A32D2D',
    accentColor: '#F0A0A0',
    dotColor: '#E06060',
    description: 'Tiempo de descanso y reflexión profunda',
    energy: 'Baja',
    mood: 'Introspectiva',
  },
  folicular: {
    name: 'Folicular',
    emoji: '🌱',
    days: '6–13',
    bgColor: '#E6F1FB',
    textColor: '#185FA5',
    accentColor: '#90BEE8',
    dotColor: '#4A9FD4',
    description: 'Energía creciente y mayor creatividad',
    energy: 'Creciente',
    mood: 'Optimista',
  },
  ovulatoria: {
    name: 'Ovulatoria',
    emoji: '✨',
    days: '14–16',
    bgColor: '#FAEEDA',
    textColor: '#BA7517',
    accentColor: '#E8C070',
    dotColor: '#D4940A',
    description: 'Pico de energía, comunicación y carisma',
    energy: 'Máxima',
    mood: 'Sociable',
  },
  lutea: {
    name: 'Lútea',
    emoji: '🍂',
    days: '17–28',
    bgColor: '#EEEDFE',
    textColor: '#534AB7',
    accentColor: '#B0A8F0',
    dotColor: '#7A6FD4',
    description: 'Introspección, sensibilidad y autocuidado',
    energy: 'Variable',
    mood: 'Reflexiva',
  },
}
